config/routes.rb
require 'trade_tariff_frontend'

TradeTariffFrontend::Application.routes.draw do
  scope path: "#{APP_SLUG}" do
    get "/", to: redirect("https://www.gov.uk/trade-tariff", status: 302)
    get "healthcheck", to: "healthcheck#check"
    get "opensearch", to: "pages#opensearch", constraints: { format: :xml }
    get "terms", to: "pages#terms"
    get "cookies", to: "pages#cookies"
    get "geographical_areas", to: "geographical_areas#index", as: :geographical_areas
    match "/search", to: "search#search", as: :perform_search, via: [:get, :post]
    match "a-z-index/:letter", to: "search_references#show",
          via: :get,
          as: :a_z_index,
          constraints: { letter: /[a-z]{1}/i }

    constraints TradeTariffFrontend::ApiConstraints.new(
      TradeTariffFrontend.accessible_api_endpoints
    ) do
      match ':endpoint/(*path)',
        via: :get,
        to: TradeTariffFrontend::RequestForwarder.new(
          host: Rails.application.config.api_host,
          api_request_path_formatter: ->(path) {
            path.gsub("#{APP_SLUG}/", "")
          }
        )
    end

    resources :sections, only: [:index, :show]
    resources :chapters, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'chapters'
    end
    resources :headings, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'headings'
    end
    resources :commodities, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'commodities'
    end
  end

  root to: redirect("https://www.gov.uk/trade-tariff", status: 302)

  get "/robots.:format", to: "pages#robots"
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/503", to: "errors#maintenance", via: :all
end

app/models/heading.rb
require 'api_entity'
require 'declarable'
require 'changeable'

class Heading < GoodsNomenclature
  include Models::Changeable
  include Models::Declarable

  has_many :commodities, class_name: 'Commodity'
  has_many :children, class_name: 'Heading'

  attr_accessor :leaf, :declarable

  alias :leaf? :leaf
  alias :declarable? :declarable

  def eql?(other_heading)
    self.goods_nomenclature_item_id == other_heading.goods_nomenclature_item_id
  end

  def ==(other_heading)
    self.goods_nomenclature_item_id == other_heading.goods_nomenclature_item_id
  end

  def hash
    goods_nomenclature_item_id.to_i
  end

  def commodity_code
    code.first(10)
  end

  def display_short_code
    code[2..3]
  end
  alias :heading_display_short_code :display_short_code

  def display_export_code
    code[0..-3]
  end

  def short_code
    code.first(4)
  end

  # There are no consigned declarable headings
  def consigned?
    false
  end

  def to_param
    short_code
  end

  def footnotes
    [import_measures.map(&:footnotes).select(&:present?) + export_measures.map(&:footnotes).select(&:present?)].flatten
  end

  def to_s
    formatted_description || description
  end
end

app/controllers/headings/changes_controller.rb
module Headings
  class ChangesController < ::ChangesController

    private

    def heading
      @heading ||= Heading.find(params[:heading_id], query_params)
    end

    def changeable
      @changeable ||= HeadingPresenter.new(heading)
    end

    def change_url(*)
      heading_url(heading)
    end
  end
end

app/controllers/headings_controller.rb
class HeadingsController < GoodsNomenclaturesController
  def show
    @heading = HeadingPresenter.new(Heading.find(params[:id], query_params))
    @commodities = HeadingCommodityPresenter.new(@heading.commodities)
    @back_path = "#{chapters_path}/#{@heading.chapter.short_code}"
  end
end

app/views/headings/_heading.html.erb
<% if heading.leaf? %>
  <tr>
    <td>
      <div class="heading-code">
        <div class="code-text"><%= heading.display_short_code %></div>
      </div>
    </td>
    <td>
      <%= link_to heading.formatted_description.html_safe, heading_path(heading, request.query_parameters.symbolize_keys) %>
    </td>
  </tr>
<% else %>
  <tr>
    <td class="heading-subtitle" colspan="2"><%= heading %></td>
  </tr>
  <%= render heading.children %>
<% end %>

app/views/headings/index.html.erb
<div class='browse-sections core-content group'>
  <nav>
    <ul>
      <li>
        <strong>Section</strong>:
        <%= link_to @section, section_chapters_path(@section) %>
      </li>
      <li>
        <strong>Headings in</strong>:
        <%= link_to @chapter, section_chapter_headings_path(@section, @chapter) %>
      </li>
    </ul>
  </nav>

  <h2>Headings in this chapter</h2>

  <table>
    <thead>
      <tr>
        <td>
          <strong>No</strong>
        </td>
        <td>
          <strong>Description</strong>
        </td>
        <td>
          <strong>Footnotes</strong>
        </td>
        <td>
          <strong>Your Notes</strong>
        </td>
      </tr>
    </thead>
    <tbody>
      <%= render @headings %>
    </tbody>
  </table>
</div>

app/views/headings/show.html.erb
<% content_for :title, "#{@heading} - Trade Tariff - GOV.UK" %>
<% content_for :head do %>
  <link rel='alternate' type='application/json' href='<%= heading_url(@heading, format: :json) %>' title='Heading information page in JSON format' />
<% end %>

<% if @heading.declarable? %>
  <%= render 'declarables/declarable', declarable: @heading %>
<% else %>
  <h2 class="heading-small">Choose the commodity code below that best matches your goods to see more information</h2>
  <p>If your item is not listed by name, it may be shown under what it's used for, what it's made from or 'other'.</p>
  <%= render 'shared/tariff_breadcrumbs', heading: @heading %>
  <article class="tariff">
    <div class="tree-key">
      <div class="chapter-code">
        <div class="code-text"><%= @heading.chapter_short_code %></div>
      </div>
      <div class="heading-code">
        <div class="code-text"><%= @heading.heading_display_short_code %></div>
      </div>
      <div class="key-text">Heading code</div>
    </div>
    <div class="commodity-tree">
      <p class="commodity-tree-note"><span>The number following each commodity's </span><em class="description">Description</em><span> is its </span><em class="commcode">Commodity code</em></p>
      <ul class="commodities js-commodities">
        <%= render @commodities.root_commodities %>
      </ul>
    </div>
  </article>
<% end %>