config/routes.rb
require 'trade_tariff_frontend'

TradeTariffFrontend::Application.routes.draw do
  scope path: "#{APP_SLUG}" do
    get "/", to: redirect("https://www.gov.uk/trade-tariff", status: 302)
    get "healthcheck", to: "healthcheck#check"
    get "opensearch", to: "pages#opensearch", constraints: { format: :xml }
    get "terms", to: "pages#terms"
    get "cookies", to: "pages#cookies"
    get "geographical_areas", to: "geographical_areas#index", as: :geographical_areas
    match "/search", to: "search#search", as: :perform_search, via: [:get, :post]
    match "a-z-index/:letter", to: "search_references#show",
          via: :get,
          as: :a_z_index,
          constraints: { letter: /[a-z]{1}/i }

    constraints TradeTariffFrontend::ApiConstraints.new(
      TradeTariffFrontend.accessible_api_endpoints
    ) do
      match ':endpoint/(*path)',
        via: :get,
        to: TradeTariffFrontend::RequestForwarder.new(
          host: Rails.application.config.api_host,
          api_request_path_formatter: ->(path) {
            path.gsub("#{APP_SLUG}/", "")
          }
        )
    end

    resources :sections, only: [:index, :show]
    resources :chapters, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'chapters'
    end
    resources :headings, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'headings'
    end
    resources :commodities, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'commodities'
    end
  end

  root to: redirect("https://www.gov.uk/trade-tariff", status: 302)

  get "/robots.:format", to: "pages#robots"
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/503", to: "errors#maintenance", via: :all
end

app/models/search.rb
require 'api_entity'

class Search
  include ApiEntity

  attr_accessor :t,       # search text query
                :country, # search country
                :day,
                :month,
                :year,
                :as_of    # legacy format for specifying date

  delegate :today?, to: :date

  def perform
    response = self.class.post("/search", body: { t: t, as_of: date.to_s(:db) })

    raise ApiEntity::Error if response.code == 500

    Outcome.new(response)
  end

  def t=(t)
    @t = t.to_s.gsub(/(\[|\])/,'')
  end

  def q
    'trade_tariff'
  end

  def countries
    return [ geographical_area ].compact
  end

  def geographical_area
    GeographicalArea.cached_countries.detect do |country|
      country.id == attributes['country']
    end
  end

  def date
    @date ||= if as_of.present?
                TariffDate.new(as_of)
              else
                TariffDate.parse(attributes.slice(*TariffDate::DATE_KEYS))
              end
  end

  def filtered_by_date?
    date.date != Date.current
  end

  def filtered_by_country?
    country.present?
  end

  def any_filter_active?
    filtered_by_date? || filtered_by_country?
  end

  def contains_search_term?
    t.present?
  end

  def query_attributes
    { 'day'  => date.day,
      'year' => date.year,
      'month' => date.month }.merge(attributes.slice(:country))
  end

  def to_s
    t
  end

  def id
    t
  end
end

app/models/search/base_match.rb
require 'api_entity'

class Search
  class BaseMatch
    include ApiEntity

    private

    def self.array_attr_reader(*args)
      args.each do |arg|
        define_method(arg.to_sym) do
          instance_variable_get("@#{arg}").presence ||[]
        end
      end
    end

    def self.array_attr_writer(*names)
      names.each do |name|
        define_method("#{name}=") do |entry_data|
          instance_variable_set("@#{name}", entry_data.map{|ed| name.to_s.singularize.capitalize.constantize.new(ed['_source'].has_key?('reference') ? ed['_source']['reference'] : ed['_source'])})
        end
      end
    end
  end
end

app/models/search/goods_nomenclature_match.rb
require 'api_entity'
require 'ostruct'
require 'search/base_match'

class Search
  class GoodsNomenclatureMatch < BaseMatch
    BLANK_RESULT = OpenStruct.new(
      sections: [], chapters: [], headings: [], commodities: []
    )

    array_attr_reader :sections, :chapters, :headings, :commodities
    array_attr_writer :sections, :chapters, :headings, :commodities

    def commodities=(commodity_data)
      @commodities = commodity_data.map { |cd| Commodity.new(cd["_source"]) }

      self.commodity_headings = @commodities
    end

    def commodity_headings
      @commodity_headings.presence || []
    end

    # Extract Headings from Commodity object as we need to build
    # a tree for representation.
    # Also, add commodity to heading's commodity array so that they could
    # be listed in the tree.
    def commodity_headings=(commodities)
      @commodity_headings ||= []

      commodities.each do |commodity|
        if existing_heading = find_heading(commodity.heading)
          existing_heading.add_commodity(commodity)
        else
          @commodity_headings << build_heading_from(commodity).tap {|heading|
            heading.add_commodity(commodity)
          }
        end
      end
    end

    def resulting_headings
      (headings + commodity_headings).sort_by(&:goods_nomenclature_item_id).uniq
    end

    def any?
      [headings, commodities, chapters, sections].any? {|entity_group| entity_group.any? }
    end

    def all
      [headings, commodities, chapters, sections].flatten
    end

    def size
      all.size
    end

    private

    def find_heading(heading_for_search)
      (headings + commodity_headings).detect { |heading| heading == heading_for_search }
    end

    def build_heading_from(commodity)
      Heading.new(commodity.heading.attributes.merge(chapter: commodity.chapter.attributes,
                                                     section: commodity.section.attributes))
    end
  end
end

app/models/search/outcome.rb
require 'api_entity'

class Search
  class Outcome
    include ApiEntity

    attr_writer :entry, :type

    def exact_match?
      @type == "exact_match"
    end

    def to_param
      {
        controller: @entry['endpoint'],
        action: :show,
        id: @entry['id']
      }
    end

    def any?
      (goods_nomenclature_match.present? && goods_nomenclature_match.any?) ||
      (reference_match.present? && reference_match.any?)
    end

    def goods_nomenclature_match
      @goods_nomenclature_match || GoodsNomenclatureMatch::BLANK_RESULT
    end

    def reference_match
      @reference_match || ReferenceMatch::BLANK_RESULT
    end

    def goods_nomenclature_match=(entries)
      @goods_nomenclature_match ||= GoodsNomenclatureMatch.new(entries)
    end

    def reference_match=(entries)
      @reference_match ||= ReferenceMatch.new(entries)
    end

    def all_reference_matches
      [reference_match.chapters, reference_match.headings].flatten
    end

    def all_gn_matches
      [goods_nomenclature_match.chapters, goods_nomenclature_match.resulting_headings].flatten
    end

    def gn_chapters_without_duplicates
      # TODO - Do we need this if we're removing duplicates below anyway?
      goods_nomenclature_match.chapters.delete_if { |gc| reference_match.chapters.select { |rc| rc.code == gc.code }.any? }
    end

    def gn_headings_without_duplicates
      goods_nomenclature_match.resulting_headings.delete_if { |gh| reference_match.headings.select { |rh| rh.code == gh.code }.any? }
    end

    def matches_by_chapter(chapters, headings)
      results = {}

      chapters.each do |chapter|
        results[chapter.short_code] = [chapter, []]
      end

      headings.sort_by! { |h| h.short_code }
      headings.each do |heading|
        result = results[heading.chapter.short_code]
        result_existing_headings = result.nil? ? [] : result[1]
        results[heading.chapter.short_code] = [heading.chapter, result_existing_headings.push(heading)]
      end
      sorted_results = results.sort_by { |k, v| k }
      sorted_results.to_a
    end

    def reference_matches_by_chapter
      matches_by_chapter(reference_match.chapters, reference_match.headings)
    end

    def gn_matches_without_duplicates_by_chapter
      gn_matches_by_chapter = matches_by_chapter(gn_chapters_without_duplicates, gn_headings_without_duplicates)

      gn_matches_by_chapter.delete_if do |gn|
        reference_matches_by_chapter.select { |ref| ref[0] == gn[0] } && gn[1][1].blank?
      end
    end

    def all
      [reference_match.all, goods_nomenclature_match.all].flatten
    end

    def size
      all.size
    end
  end
end

app/models/search/reference_match.rb
require 'api_entity'
require 'ostruct'
require 'search/base_match'

class Search
  include ApiEntity

  class ReferenceMatch < BaseMatch
    BLANK_RESULT = OpenStruct.new(
      sections: [], chapters: [], headings: [], commodities: []
    )

    array_attr_reader :sections, :chapters, :headings, :commodities
    array_attr_writer :sections, :chapters, :headings, :commodities

    def any?
      [headings, chapters, sections, commodities].any? { |entity_group| entity_group.any? }
    end

    def all
      (sections + chapters + headings + commodities).flatten
    end

    def size
      all.size
    end
  end
end

app/controllers/search_controller.rb
require 'addressable/uri'

class SearchController < ApplicationController
  def search
    @results = @search.perform

    respond_to do |format|
      format.html {
        if @search.contains_search_term?
          redirect_to url_for(@results.to_param.merge(url_options)) if @results.exact_match?
        else
          if request.referer
            back_url = Addressable::URI.parse(request.referer)
            back_url.query_values ||= {}
            back_url.query_values = back_url.query_values.merge(@search.query_attributes)
            return_to = back_url.to_s
          else
            return_to = sections_path
          end

          anchor = if params.dig(:search, :anchor).present?
            if params[:search][:anchor] == 'import'
              '#import'
            else
              '#export'
            end
          else
            ''
          end

          redirect_to(return_to + anchor)
        end
      }

      format.json {
        render json: SearchPresenter.new(@search, @results)
      }

      format.atom
    end
  end
end

app/views/search/_commodity.html.erb
<li>
  <div class="commodity">
    <%= format_full_code(commodity) %>
    <a href="<%= commodity_path(commodity) %>"><%= commodity.description.html_safe %></a>
  </div>
</li>

app/views/search/_result.html.erb
<% chapter = result[1][0] %>
<% headings = result[1][1] %>
<li>
  <div class="chapter">
    <div class="chapter-code">
      <div class="code-text"><%= chapter.short_code %></div>
    </div>
    <a href="<%= chapter_path(chapter) %>"><%= chapter.description.html_safe %></a>
  </div>
  <% if headings.any? %>
    <ul>
      <% headings.each do |heading| %>
        <li>
          <div class="heading">
            <div class="heading-code">
              <div class="code-text"><%= heading.heading_display_short_code %></div>
            </div>
            <a href="<%= heading_path(heading) %>"><%= heading.description.html_safe %></a>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</li>

app/views/search/_section.html.erb
<li>
  <div class="section">Section <%= section.numeral %>: <%= link_to section, section_path(section) %></div>
</li>

app/views/search/search.html.erb
<h1 class="heading-medium">Search results for &lsquo;<%= @search.t %>&rsquo;</h1>
<article class="search-results">
  <% if @results.any? %>
    <% if @results.reference_match.commodities.any? %>
      <h2 class="heading-small">Commodities matching &lsquo;<%= @search %>&rsquo;</h2>
      <ul class="results-subset js-results-subset">
        <%= render partial: 'search/commodity', collection: @results.reference_match.commodities %>
      </ul>
    <% end %>

    <% if @results.reference_matches_by_chapter.any? %>
      <h2 class="heading-small">Results matching &lsquo;<%= @search %>&rsquo;</h2>
      <ul class="results-subset js-results-subset">
        <%= render partial: 'search/result', collection: @results.reference_matches_by_chapter %>
      </ul>
    <% end %>

    <% if @results.gn_matches_without_duplicates_by_chapter.any? %>
      <h2 class="heading-small">Other results containing the term &lsquo;<%= @search %>&rsquo;</h2>
      <ul class="results-subset js-results-subset">
        <%= render partial: 'search/result', collection: @results.gn_matches_without_duplicates_by_chapter %>

      </ul>
    <% end %>

    <% if @results.reference_match.sections.any? %>
      <h2 class="heading-small">Sections matching &lsquo;<%= @search %>&rsquo;</h2>
      <ul class="results-subset js-results-subset">
        <%= render partial: 'search/section', collection: @results.reference_match.sections %>
      </ul>
    <% end %>
  <% else %>
    <p>There are no results matching your query.</p>
    <div class="panel panel-border-wide">
      <p><strong>Please search again and consider:</strong></p>
      <ul class="list list-bullet">
        <li>Searching what the item is used for or made from</li>
        <li>Broadening your search criteria</li>
        <li>Checking your spelling</li>
        <li>Browsing the <%= link_to 'A-Z of Classified Goods', a_z_index_path(letter: 'a') %></li>
      </ul>
    </div>
  <% end %>
</article>