config/routes.rb
require 'trade_tariff_frontend'

TradeTariffFrontend::Application.routes.draw do
  scope path: "#{APP_SLUG}" do
    get "/", to: redirect("https://www.gov.uk/trade-tariff", status: 302)
    get "healthcheck", to: "healthcheck#check"
    get "opensearch", to: "pages#opensearch", constraints: { format: :xml }
    get "terms", to: "pages#terms"
    get "cookies", to: "pages#cookies"
    get "geographical_areas", to: "geographical_areas#index", as: :geographical_areas
    match "/search", to: "search#search", as: :perform_search, via: [:get, :post]
    match "a-z-index/:letter", to: "search_references#show",
          via: :get,
          as: :a_z_index,
          constraints: { letter: /[a-z]{1}/i }

    constraints TradeTariffFrontend::ApiConstraints.new(
      TradeTariffFrontend.accessible_api_endpoints
    ) do
      match ':endpoint/(*path)',
        via: :get,
        to: TradeTariffFrontend::RequestForwarder.new(
          host: Rails.application.config.api_host,
          api_request_path_formatter: ->(path) {
            path.gsub("#{APP_SLUG}/", "")
          }
        )
    end

    resources :sections, only: [:index, :show]
    resources :chapters, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'chapters'
    end
    resources :headings, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'headings'
    end
    resources :commodities, only: [:index, :show] do
      resources :changes,
                only: [:index],
                defaults: { format: :atom },
                module: 'commodities'
    end
  end

  root to: redirect("https://www.gov.uk/trade-tariff", status: 302)

  get "/robots.:format", to: "pages#robots"
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "/503", to: "errors#maintenance", via: :all
end

app/views/shared/_country_picker.erb
<%= form_for controller, method: :post, url: url, namespace: anchor do |f| %>
  <fieldset class="country-picker js-country-picker box font-xsmall">
    <div class="country-picker-container">
      <%= f.hidden_field :anchor, value: anchor %>
      <%= f.label :country, 'Trade between the UK and' %>
      <%= f.select :country, f.object.countries.map{ |c| [c.long_description, c.id] }, { include_blank: 'All countries' }, class: 'js-country-picker-select' %>
      <a class="reset-country-picker" href="#reset-country-picker" title="Reset country picker" rel="nofollow">Reset<span class="long-text">&nbsp;to all countries</span></a>
    </div>
    <%= f.button 'Set country', class: 'button search-submit' %>
  </fieldset>
<% end %>

app/views/shared/_fullstory_snippet.html.erb
<% if Rails.env.production? %>
  <% content_for :head do %>
    <script type='text/javascript'>
      window['_fs_debug'] = false;
      window['_fs_host'] = 'www.fullstory.com';
      window['_fs_org'] = '1ZGTD';
      window['_fs_namespace'] = 'FS';
      (function(m,n,e,t,l,o,g,y){
        if (e in m && m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].'); return;}
        g=m[e]=function(a,b){g.q?g.q.push([a,b]):g._api(a,b);};g.q=[];
        o=n.createElement(t);o.async=1;o.src='https://'+_fs_host+'/s/fs.js';
        y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
        g.identify=function(i,v){g(l,{uid:i});if(v)g(l,v)};g.setUserVars=function(v){g(l,v)};
        g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
        g.clearUserCookie=function(c,d,i){if(!c || document.cookie.match('fs_uid=[`;`]*`[`;`]*`[`;`]*`')){
        d=n.domain;while(1){n.cookie='fs_uid=;domain='+d+
        ';path=/;expires='+new Date(0);i=d.indexOf('.');if(i<0)break;d=d.slice(i+1)}}};
      })(window,document,window['_fs_namespace'],'script','user');
    </script>
  <% end %>

  <% content_for :body_end do %>
    <script type="text/javascript" charset="utf-8">
      $(window).unload(function() {
        FS.clearUserCookie();
      });
    </script>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<% if controller_name == 'commodities' && action_name == 'show' || controller_name == 'headings' && action_name == 'show' && @heading.declarable? %>
  <header>
    <a class="back-to-previous" href="<%= @back_path %>">Back <span class="visuallyhidden"> to the list of commodities</span></a>
    <h1 class="heading-large">Commodity information</h1>
    <%= form_for @search, method: :post, url: perform_search_path, html: { class: "tariff-search #{@section_css}", id: "new_search" } do |f| %>
      <div class="grid-row">
        <div class="column-full">
          <div class="search-header">
            <div class="searchfield form-group">
              <fieldset class="js-date-picker date-picker font-xsmall form-group">
                <span class="fields">This tariff is for
                  <label class="visuallyhidden" for="tariff_date_day">Day</label>
                  <%= select_day(f.object.date, {}, { id: 'tariff_date_day', name: 'day', class: 'js-select' }) %>
                  <label class="visuallyhidden" for="tariff_date_month">Month</label>
                  <%= select_month(f.object.date, {}, { id: 'tariff_date_month', name: 'month', class: 'js-select' }) %>
                  <label class="visuallyhidden" for="tariff_date_year">Year</label>
                  <%= select_year(f.object.date, {end_year: 2008, start_year: Date.current.year + 1 }, { id: 'tariff_date_year', name: 'year', class: 'js-select' }) %>&emsp;
                  <a class="submit" role="button" href="#set-date" title="set date" rel="nofollow">Set date</a>
                </span>
                <span class="text <%= @section_css %>">
                  This tariff is for <%= @search.date.to_formatted_s(:long) %>&emsp;
                  <a href="#change-date" title="change date" rel="nofollow">Change date</a>
                </span>
              </fieldset>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </header>
<% else %>
  <header>
    <h1 class="heading-large"><a href="<%= sections_path %>">Trade Tariff: look up commodity codes, duty and VAT rates</a></h1>
  </header>
  <%= form_for @search, method: :post, url: perform_search_path, html: { class: "tariff-search #{@section_css}", id: "new_search" } do |f| %>
    <div class="grid-row">
      <div class="column-two-thirds">
        <div class="search-header js-search-header">
          <div class="searchfield form-group">
            <fieldset class="search-input">
              <%= f.hidden_field :q, name: 'q' %>
              <%= f.label :t, "Search the tariff", class: 'form-label' %>
              <%= f.text_field :t, required: false,
                          size: 21,
                          placeholder: "Enter the name of the goods or commodity code",
                          name: 't',
                          class: 'form-control'  %>
            </fieldset>
            <fieldset class="search-submit">
              <%= f.button 'Search', class: 'button' %>
            </fieldset>
          </div>

          <fieldset class="js-date-picker date-picker font-xsmall form-group">
            <span class="fields">This tariff is for
              <label class="visuallyhidden" for="tariff_date_day">Day</label>
              <%= select_day(f.object.date, {}, { id: 'tariff_date_day', name: 'day', class: 'js-select' }) %>
              <label class="visuallyhidden" for="tariff_date_month">Month</label>
              <%= select_month(f.object.date, {}, { id: 'tariff_date_month', name: 'month', class: 'js-select' }) %>
              <label class="visuallyhidden" for="tariff_date_year">Year</label>
              <%= select_year(f.object.date, {end_year: 2008, start_year: Date.current.year + 1 }, { id: 'tariff_date_year', name: 'year', class: 'js-select' }) %>&emsp;
              <a class="submit change-date-link" role="button" href="#set-date" title="set date" rel="nofollow">Set date</a>
            </span>
            <span class="text <%= @section_css %>">
              This tariff is for <%= @search.date.to_formatted_s(:long) %>&emsp;
              <a href="#change-date" class="change-date-link" title="change date" rel="nofollow">Change date</a>
            </span>
          </fieldset>

        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_notes.html.erb
<% section_note ||= false
chapter_note ||= false %>

<% if section_note || chapter_note %>
  <article class="notes">

    <% if section_note && chapter_note %>
      <h2 class="heading-small">There are important section notes and chapter notes for this part of the tariff:</h2>
    <% end %>

    <% if chapter_note %>
      <div id="chapter-notes">
        <% if section_note %>
          <h3 class="heading-small">Chapter notes</h3>
        <% else %>
          <h2 class="heading-small">There are important chapter notes for this part of the tariff:</h2>
        <% end %>
        <%= govspeak(chapter_note) %>
      </div>
    <% end %>
    <% if section_note %>
      <div id="section-notes">
        <% if chapter_note %>
          <h3 class="heading-small">Section notes</h3>
        <% else %>
          <h2 class="heading-small">There are important section notes for this part of the tariff:</h2>
        <% end %>
        <%= govspeak(section_note) %>
      </div>
    <% end %>

  </article>
<% end %>

app/views/shared/_tariff_breadcrumbs.html.erb
<% section ||= false
chapter ||= false
heading ||= false
declarable ||= false %>

<div class="tariff-breadcrumbs js-tariff-breadcrumbs clt font-xsmall">
  <nav>
    <%= link_to "All sections", sections_path(request.query_parameters.symbolize_keys), class: "all-sections-link" %>

    <% if declarable %>
      <div class="desktop-only">
        <ul>
          <li>
            <%= link_to "Section #{declarable.section_numeral}: #{declarable.section}", section_path(declarable.section, request.query_parameters.symbolize_keys), class: "section-link" %>
            <ul>
              <li class="chapter-li">
                <div class="chapter-code">
                  <div class="code-text"><%= declarable.chapter_short_code %></div>
                </div>
                <%= link_to declarable.chapter, chapter_path(declarable.chapter, request.query_parameters.symbolize_keys) %>
                <ul>
                  <li class="heading-li">
                    <div class="heading-code">
                      <div class="code-text"><%= declarable.heading_display_short_code %></div>
                    </div>
                    <% if declarable.show_commodity_tree? %>
                      <%= link_to declarable.heading.to_s.html_safe, heading_path(declarable.heading, request.query_parameters.symbolize_keys) %>
                      <%= commodity_tree(declarable, declarable.ancestors) %>
                    <% else %>
                      <%= declarable_heading(declarable) %>
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="mobile-only">
        <ul class="js-full-tree">
          <li>
            <%= link_to "Section #{declarable.section_numeral}: #{declarable.section}", section_path(declarable.section, request.query_parameters.symbolize_keys), class: "section-link" %>
            <ul>
              <li class="chapter-li">
                <div class="chapter-code">
                  <div class="code-text"><%= declarable.chapter_short_code  %></div>
                </div>
                <%= link_to declarable.chapter, chapter_path(declarable.chapter, request.query_parameters.symbolize_keys) %>
                <ul>
                  <li class="heading-under-chapter-li">
                    <div class="heading-code">
                      <div class="code-text"><%= declarable.heading_display_short_code %></div>
                    </div>
                    <% if declarable.show_commodity_tree? %>
                      <%= link_to declarable.heading.to_s.html_safe, heading_path(declarable.heading, request.query_parameters.symbolize_keys) %>
                      <%= commodity_tree(declarable, declarable.ancestors) %>
                    <% else %>
                      <%= declarable_heading(declarable) %>
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
        <ul class="js-summary-tree">
          <li>
            <a href="#" class="show-full-tree-link js-show-full-tree-link">[Show all]</a>
            <ul>
              <li class="commodity-li">
                <% if declarable.show_commodity_tree? %>
                  <%= commodity_heading_full(declarable) %>
                <% else %>
                  <%= declarable_heading_full(declarable) %>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </div>

    <% elsif heading %>
      <div class="desktop-only">
        <ul>
          <li>
            <%= link_to "Section #{heading.section.numeral}: #{heading.section.title}", section_path(heading.section, request.query_parameters.symbolize_keys), class: "section-link" %>
            <ul>
              <li class="chapter-li">
                <div class="chapter-code">
                  <div class="code-text"><%= heading.chapter_short_code  %></div>
                </div>
                <%= link_to heading.chapter, chapter_path(heading.chapter, request.query_parameters.symbolize_keys) %>
                <ul>
                  <li class="heading-li">
                    <div class="heading-code">
                      <div class="code-text"><%= heading.heading_display_short_code %></div>
                    </div>
                    <h1><%= heading.formatted_description.html_safe %></h1>
                    <div class="feed"><%= link_to 'Changes', heading_changes_path(@heading.declarable, format: :atom), rel: "nofollow" %></div>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="mobile-only">
        <ul class="js-full-tree">
          <li>
            <%= link_to "Section #{heading.section.numeral}: #{heading.section.title}", section_path(heading.section, request.query_parameters.symbolize_keys), class: "section-link" %>
            <ul>
              <li class="chapter-li">
                <div class="chapter-code">
                  <div class="code-text"><%= heading.chapter_short_code  %></div>
                </div>
                <%= link_to heading.chapter, chapter_path(heading.chapter, request.query_parameters.symbolize_keys) %>
                <ul>
                  <li class="heading-li">
                    <div class="heading-code">
                      <div class="code-text"><%= heading.heading_display_short_code %></div>
                    </div>
                    <h1><%= heading.formatted_description.html_safe %></h1>
                    <div class="feed"><%= link_to 'Changes', heading_changes_path(@heading.declarable, format: :atom), rel: "nofollow" %></div>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
        <ul class="mobile-only js-summary-tree">
          <li>
            <a href="#" class="show-full-tree-link js-show-full-tree-link">[Show all]</a>
            <ul>
              <li class="chapter-and-heading-li">
                <div class="chapter-code">
                  <div class="code-text"><%= heading.chapter_short_code  %></div>
                </div><div class="heading-code">
                  <div class="code-text"><%= heading.heading_display_short_code %></div>
                </div>
                <h1><%= heading.formatted_description.html_safe %></h1>
                <div class="feed"><%= link_to 'Changes', heading_changes_path(@heading.declarable, format: :atom), rel: "nofollow" %></div>
              </li>
            </ul>
          </li>
        </ul>
      </div>

    <% elsif chapter %>
      <ul>
        <li>
          <%= link_to "Section #{chapter.section_numeral}: #{chapter.section}", section_path(chapter.section, request.query_parameters.symbolize_keys), class: "section-link" %>
          <ul>
            <li class="chapter-li">
              <div class="chapter-code">
                <div class="code-text"><%= chapter.short_code %></div>
              </div>
              <h1><%= chapter %></h1>
              <div class="feed"><%= link_to 'Changes', chapter_changes_path(@chapter, format: :atom), rel: "nofollow" %></div>
            </li>
          </ul>
        </li>
      </ul>

    <% elsif section %>
      <ul>
        <li>
          <h1><%= "Section #{section.numeral}: #{section}" %></h1>
        </li>
      </ul>
    <% end %>
  </nav>
</div>